apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcName }}
  namespace: {{ .Values.nameSpace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName}}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30082
  
